version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  bot:
    build: .
    container_name: galactica_schedule_bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/code
    restart: unless-stopped
    command: python src/telegram_bot/main.py

volumes:
  redis_data:
